framework:
  messenger:
    failure_transport: failed

    transports:
      async_priority_high:
        dsn: '%env(RABBITMQ_URL)%'
        retry_strategy:
          max_retries: 30
          delay: 1000
          multiplier: 2
          max_delay: 0

      async_priority_low:
        dsn: '%env(RABBITMQ_URL)%'
        retry_strategy:
          max_retries: 30
          delay: 1000
          multiplier: 2
          max_delay: 0

      failed: 'doctrine://default?queue_name=failed'

    routing:
      App\Message\CreateGasStationMessage: async_priority_high
      App\Message\CreateGasServiceMessage: async_priority_low
      App\Message\CreateGasPriceMessage: async_priority_low
      App\Message\UpdateGasStationAddress: async_priority_low
