controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

admin:
    resource: ../src/Admin/
    type: annotation

authentication_token:
    path: /api/authentication_token
    methods: [ 'POST' ]